### PR TITLE
Remove API_HOST, WHITELISTED_IPS, associated code, and documentation

### LINKED ISSUE #1692: "next" parameter in API results is wrong in production, and also undocumented
```
curl 'https://api.data.gov/gsa/calc/rates/?q=engineer&query_type=match_all'
```

(Aside: I'm surprised this even works--I thought an `api_key` had to be provided here, but I guess not?)

The JSON response will include a `next` key whose value is:

```
https://calc-prod.app.cloud.gov/api/rates/?page=2&q=engineer&query_type=match_all
```

However, running `curl` on it returns a 403 with the response `{"detail":"Authentication credentials were not provided."}`.

I assume this is because `calc-prod.app.cloud.gov`'s `/api/` endpoint filters by IP address, since it's only supposed to be accessed by the API umbrella reverse proxy at api.data.gov.

Ideally, the `next` argument should point at `api.data.gov` and the correct path.

As a workaround, though, clients can just parse the `page` querystring argument from `next` and construct the next URL manually by taking their original request and adding the page to its querystring.

Aside from that, I also noticed that we don't seem to document `next` in our API docs.

### LINKED ISSUE #1694: Production site API pages are not loading CSS/JS/image static assets
When visiting https://api.data.gov/gsa/calc/rates/, we should see a nice Django Rest Framework page that looks something like:

screen shot 2018-04-03 at 9 11 37 am

However, we get an unstyled page that looks like:

screen shot 2018-04-03 at 9 09 31 am

Here's what the console shows:

screen shot 2018-04-03 at 9 13 43 am

### PR DESCRIPTION
**Pull request by jseppi**
As described in #1747, we don't really see any benefit in using the api.data.gov API Umbrella instance to proxy requests to our own app, and it causes a few other bugs.

This PR removes the `API_HOST` and `WHITELISTED_IPS` environment variables and the associated code for proxying API requests and whitelisting only specific IPs (those of api.data.gov) to the "real" API path.  Documentation around those settings and the usage of api.data.gov is also removed.

While they will be harmless, it would be good to remove the `API_HOST` and `WHITELISTED_IPS` vars from `calc-env` in each of our cloud.gov spaces, but **this should only be done upon promotion of these code changes** to each space.

closes #1692 and closes #1694

### CODE REVIEW

File: frontend/source/js/data-explorer/constants.js [hunk 1]
```diff
@@ -124,7 +124,3 @@ export const QUERY_TYPE_LABELS = {
 };
 
 export const MAX_QUERY_LENGTH = 255;
-
-export const API_HOST = window.API_HOST;
-
-export const API_RATES_CSV = `${API_HOST}rates/csv/`;
```
Comment (toolness) [inline frontend/source/js/data-explorer/constants.js]: So the one thing I like about keeping these routes in their own separate file is just that they're all in one place, so maintainers (hopefully) know where to look if they decide to change any routes on the back-end, rather than relying on grepping through the source code or something.  Hmmmmmmmmm.  What do you think of adding a separate module called `backend-routes.js` that has either constants or functions (if the route requires parameters) that return route strings?  Or is that going overboard?

File: docs/api.md [hunk 2]
```diff
@@ -2,34 +2,25 @@
...
+The following documentation assumes you're trying to access the API from the production instance via a tool like `curl` at `https://calc.gsa.gov/api/`.
+In development, use `http://localhost:8000/api/`.
 
 ### `/rates/`
 
 You can access labor rate information at `/rates/`.
 
 ```
-https://api.data.gov/gsa/calc/rates/
+https://calc.gsa.gov/api/rates/
```
Comment (toolness) [inline docs/api.md]: Something this is making me realize is that API requests will now go through CloudFront on production.  I don't think this currently impacts us in a negative way, but if e.g. we eventually decide to use API tokens or something, we'd have to remember to have CloudFront pass any fancy headers we use on to the origin server.

File: frontend/source/js/data-explorer/constants.js (hunk 1 above)
Comment (jseppi) [reply frontend/source/js/data-explorer/constants.js]: yeah, I'll add them back. Good point!

Comment (jseppi) [reply frontend/source/js/data-explorer/constants.js]: I ended up adding the constants to `api.js` instead of to `constants.js` or another new file. Seemed like a logical place for them to me.

**Comment by jseppi** [comment]
Added dependency on https://github.com/18F/calc/issues/1773

File: frontend/source/js/data-explorer/constants.js (hunk 1 above)
Comment (toolness) [reply frontend/source/js/data-explorer/constants.js]: Ah nice, good idea!

**Comment by jseppi** [comment]
Verification of analytics capabilities confimed in #1773!
